spring.datasource.url=jdbc:postgresql://localhost:5433/mehrdad?currentSchema=public
spring.datasource.username=mehrdad
spring.datasource.password=mehrdad
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
spring.jpa.properties.hibernate.jdbc.batch_size=50000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true